// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXPFa_j4nHI1JzD5mg1fSFREkYo3XDC5E',
    appId: '1:297529623434:web:7e0d4be741f7bfbfc5fe73',
    messagingSenderId: '297529623434',
    projectId: 'whatsapp-clone-firebase-01',
    authDomain: 'whatsapp-clone-firebase-01.firebaseapp.com',
    storageBucket: 'whatsapp-clone-firebase-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzgSEPOO7m_7pJCjyIHGTvtAss5aMltBE',
    appId: '1:297529623434:android:aeb909911aabcdf7c5fe73',
    messagingSenderId: '297529623434',
    projectId: 'whatsapp-clone-firebase-01',
    storageBucket: 'whatsapp-clone-firebase-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoAefiIy1zTvKfr8EyzJjdYACoSTRBzg0',
    appId: '1:297529623434:ios:21bdf9ee8eb9040dc5fe73',
    messagingSenderId: '297529623434',
    projectId: 'whatsapp-clone-firebase-01',
    storageBucket: 'whatsapp-clone-firebase-01.firebasestorage.app',
    iosBundleId: 'com.example.whatsappCloneGetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoAefiIy1zTvKfr8EyzJjdYACoSTRBzg0',
    appId: '1:297529623434:ios:21bdf9ee8eb9040dc5fe73',
    messagingSenderId: '297529623434',
    projectId: 'whatsapp-clone-firebase-01',
    storageBucket: 'whatsapp-clone-firebase-01.firebasestorage.app',
    iosBundleId: 'com.example.whatsappCloneGetx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXPFa_j4nHI1JzD5mg1fSFREkYo3XDC5E',
    appId: '1:297529623434:web:5f19b7565a9dbb3cc5fe73',
    messagingSenderId: '297529623434',
    projectId: 'whatsapp-clone-firebase-01',
    authDomain: 'whatsapp-clone-firebase-01.firebaseapp.com',
    storageBucket: 'whatsapp-clone-firebase-01.firebasestorage.app',
  );
}
