// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjFJlSkTJ6g5HZICIKJ0hw6-lzkMBJMQ8',
    appId: '1:1036629379530:android:6b8525a1142b95f21e2733',
    messagingSenderId: '1036629379530',
    projectId: 'todo-b07e5',
    storageBucket: 'todo-b07e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9PPwoZcJwMbzZxIFAJboK6bkh7IAq3-U',
    appId: '1:1036629379530:ios:c73158d0df9d1cc01e2733',
    messagingSenderId: '1036629379530',
    projectId: 'todo-b07e5',
    storageBucket: 'todo-b07e5.appspot.com',
    androidClientId: '1036629379530-3isaek2n7e8cdb63s3o2t60hrk9imlbe.apps.googleusercontent.com',
    iosClientId: '1036629379530-mc5rqjkfvcf71sutsmtohed6i69q6ord.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappCloneGetx',
  );

}